//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaNoche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Active
    {
        public Active()
        {
            this.Evenings = new HashSet<Evening>();
            this.Evenings1 = new HashSet<Evening>();
            this.Evenings2 = new HashSet<Evening>();
            this.Evenings3 = new HashSet<Evening>();
            this.Evenings4 = new HashSet<Evening>();
        }
    
        public int ID { get; set; }
        public string FirsName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Birthday { get; set; }
        public bool Availability { get; set; }
        public string Picture { get; set; }
        public string Summary { get; set; }
        public Nullable<int> EveningLesson_ID { get; set; }
    
        public virtual EveningLesson EveningLesson { get; set; }
        public virtual ICollection<Evening> Evenings { get; set; }
        public virtual ICollection<Evening> Evenings1 { get; set; }
        public virtual ICollection<Evening> Evenings2 { get; set; }
        public virtual ICollection<Evening> Evenings3 { get; set; }
        public virtual ICollection<Evening> Evenings4 { get; set; }
    }
}
