//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaNoche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Evening
    {
        public Evening()
        {
            this.EveningLessons = new HashSet<EveningLesson>();
        }
    
        public int ID { get; set; }
        public int EveningLessonID { get; set; }
        public System.DateTime Date { get; set; }
        public string Concept { get; set; }
        public Nullable<int> Announcer_ID { get; set; }
        public Nullable<int> DJ_ID { get; set; }
        public Nullable<int> EveningManager_ID { get; set; }
        public Nullable<int> EveningManagerAssistant_ID { get; set; }
        public Nullable<int> IntroductoryRateGuide_ID { get; set; }
    
        public virtual Active Active { get; set; }
        public virtual Active Active1 { get; set; }
        public virtual Active Active2 { get; set; }
        public virtual Active Active3 { get; set; }
        public virtual Active Active4 { get; set; }
        public virtual ICollection<EveningLesson> EveningLessons { get; set; }
    }
}
