//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediaNoche
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public Lesson()
        {
            this.Excersizes = new HashSet<Excersize>();
        }
    
        public int ID { get; set; }
        public int Level { get; set; }
        public int LessonNum { get; set; }
    
        public virtual ICollection<Excersize> Excersizes { get; set; }
    }
}
