// <auto-generated />
namespace MediaNoche.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class fix2313 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix2313));
        
        string IMigrationMetadata.Id
        {
            get { return "201510081532102_fix2313"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
